project:
  name: Hotspot Kafka API
  version: 1.0.0

server:
  port: 8080

spring:
  application:
    name: backend

  task:
    scheduling:
      pool:
        size: 4

  profiles:
    default: local

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:postgres.yml
      - classpath:redis.yml
      - classpath:kafka.yml

app:
  usage:
    db-writer:
      queue-capacity: 20000
      batch-size: 200
      batch-wait-ms: 200

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
